name: Deploy

on:
  push:
    branches:
      - main
      - preview
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  build:
    uses: ./.github/workflows/build.yml

  stage:
    uses: ./.github/workflows/stage.yml

  deploy:
    name: Deploy
    needs:
      - build
      - stage
    strategy:
      matrix:
        stack: [web]
    uses: ./.github/workflows/stack.yml
    with:
      stage: ${{ needs.stage.outputs.stage }}
      stack: ${{ matrix.stack }}