name: Deploy

on:
  pull_request:
    types:
      - closed
   
env:
  DOMAIN_NAME: danim47c.dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Cache pnpm
          uses: actions/cache@v3
          with:
            path:
              ./node_modules
            key: danim47c-pnpm
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 7
 
        - uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install
        
        - name: Set stage
          run: ${{ format('node -e "process.stdout.write(\"{0}\".slice(10).slice(0, -6))" >> $GITHUB_ENV', github.ref) }}

        - name: Turbo deploy:remove ${{ env.STAGE }}
          env:
            DOMAIN_NAME: ${{ env.DOMAIN_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: pnpm turbo run deploy:remove -- --stage ${{ env.STAGE }}