name: Get stage

on: 
  workflow_call:
    outputs:
      stage:
        description: 'Stage to deploy'
        value: ${{ steps.stage.outputs.stage }}

jobs:
  strategy:
    name: Get stage
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ env.STAGE }}
    steps:
      - name: Set pull request stage
        if: contains(github.ref, 'pull')
        run: ${{ format('node -e "process.stdout.write(\"STAGE=pr-\" + \"{0}\".slice(10).slice(0, -6))" >> $GITHUB_ENV', github.ref) }}

      - name: Set prod stage
        if: github.ref_name == 'main'
        run: echo "STAGE=prod" >> $GITHUB_ENV

      - name: Set preview stage
        if: github.ref_name == 'preview'
        run: echo "STAGE=preview" >> $GITHUB_ENV